services:
  postgres:
    image: postgres
    container_name: matix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: matix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
